name = "FiniteVolumeMethod"
uuid = "2fe254d5-11ec-4ccb-969b-f99a6a674f8e"
authors = ["Ronald @ home <r.a.remmerswaal@rug.nl>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
